version: "3.8"

services:
  app:
    container_name: doc_container_1
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
